on: push

name: Rust Stable CI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt -y update && sudo apt -y install flex bison

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal --component clippy rustfmt

      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check
