on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Rust Stable CI

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt -y update && sudo apt -y install flex bison
      - uses: actions/checkout@v4
      - uses: sensorfu/setup-rust-action@v1
        with:
          components: clippy,rustfmt
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check
